import { Product } from "@/components/ProductCard";
import electricKettleImg from "@/assets/electric-kettle.jpg";
import cutlerySetImg from "@/assets/cutlery-set.jpg";
import airFryerImg from "@/assets/air-fryer.jpg";
import vonAirFryerImg from "@/assets/von-air-fryer.jpg";
import thermosCupsComboImg from "@/assets/thermos-cups-combo.jpg";
import riceCookerImg from "@/assets/rice-cooker.jpg";
import microwaveImg from "@/assets/microwave.jpg";
import waterDispenserImg from "@/assets/water-dispenser.jpg";
import pressureCookerImg from "@/assets/pressure-cooker.jpg";
import foodProcessorImg from "@/assets/food-processor.jpg";
import toasterImg from "@/assets/toaster.jpg";
import ironBoxImg from "@/assets/iron-box.jpg";
import bedsheetsSetImg from "@/assets/bedsheets-set.jpg";
import towelSetImg from "@/assets/towel-set.jpg";
import dinnerSetImg from "@/assets/dinner-set.jpg";
import waterFilterImg from "@/assets/water-filter.jpg";
import vacuumCleanerImg from "@/assets/vacuum-cleaner.jpg";
import standingFanImg from "@/assets/standing-fan.jpg";
import wallClockImg from "@/assets/wall-clock.jpg";
import storageContainersImg from "@/assets/storage-containers.jpg";
import laundryBasketImg from "@/assets/laundry-basket.jpg";
import mopBucketSetImg from "@/assets/mop-bucket-set.jpg";
import dishRackImg from "@/assets/dish-rack.jpg";
import spiceRackImg from "@/assets/spice-rack.jpg";
import teaSetImg from "@/assets/tea-set.jpg";
import handBlenderImg from "@/assets/hand-blender.jpg";
import sandwichMakerImg from "@/assets/sandwich-maker.jpg";
import electricJugImg from "@/assets/electric-jug.jpg";
import juicerImg from "@/assets/juicer.jpg";
import deepFryerImg from "@/assets/deep-fryer.jpg";
import headphonesImg from "@/assets/headphones.jpg";
import powerBankImg from "@/assets/power-bank.jpg";
import chargingCablesImg from "@/assets/charging-cables.jpg";
import phoneHolderImg from "@/assets/phone-holder.jpg";
import hairDryerImg from "@/assets/hair-dryer.jpg";
import hairClipperImg from "@/assets/hair-clipper.jpg";
import weighingScaleImg from "@/assets/weighing-scale.jpg";
import laptopCoolerImg from "@/assets/laptop-cooler.jpg";
import wirelessMouseImg from "@/assets/wireless-mouse.jpg";
import keyboardImg from "@/assets/keyboard.jpg";
import webcamImg from "@/assets/webcam.jpg";
import laptopBagImg from "@/assets/laptop-bag.jpg";
import extensionSocketImg from "@/assets/extension-socket.jpg";
import pillowImg from "@/assets/pillow.jpg";
import duvetImg from "@/assets/duvet.jpg";
import throwPillowsImg from "@/assets/throw-pillows.jpg";
import tableLampImg from "@/assets/table-lamp.jpg";
import wallArtImg from "@/assets/wall-art.jpg";
import areaRugImg from "@/assets/area-rug.jpg";
import curtainsImg from "@/assets/curtains.jpg";
import showerCurtainImg from "@/assets/shower-curtain.jpg";
import bathroomOrganizerImg from "@/assets/bathroom-organizer.jpg";
import storageBoxImg from "@/assets/storage-box.jpg";
import shoeRackImg from "@/assets/shoe-rack.jpg";
import hangersImg from "@/assets/hangers.jpg";
import mirrorImg from "@/assets/mirror.jpg";
import trashCanImg from "@/assets/trash-can.jpg";
import yogaMatImg from "@/assets/yoga-mat.jpg";
import dumbbellsImg from "@/assets/dumbbells.jpg";
import jumpRopeImg from "@/assets/jump-rope.jpg";
import waterBottleImg from "@/assets/water-bottle.jpg";
import lunchBoxImg from "@/assets/lunch-box.jpg";
import alarmClockImg from "@/assets/alarm-clock.jpg";
import deskOrganizerImg from "@/assets/desk-organizer.jpg";
import officeChairImg from "@/assets/office-chair.jpg";
import computerDeskImg from "@/assets/computer-desk.jpg";
import bookshelfImg from "@/assets/bookshelf.jpg";
import dryingRackImg from "@/assets/drying-rack.jpg";
import ironingBoardImg from "@/assets/ironing-board.jpg";
import broomSetImg from "@/assets/broom-set.jpg";
import toiletBrushImg from "@/assets/toilet-brush.jpg";
import cleaningGlovesImg from "@/assets/cleaning-gloves.jpg";

export const products: Product[] = [
  {
    id: "1",
    name: "Stainless Steel Air Fryer",
    category: "Kitchen Appliances",
    price: 8500,
    image: airFryerImg,
    rating: 4.5,
    reviews: 124,
    description: "5L capacity air fryer with digital controls and 8 preset cooking modes. Perfect for healthy cooking with little to no oil.",
  },
  {
    id: "2",
    name: "Non-Stick Cookware Set",
    category: "Cookware",
    price: 12000,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&h=500&fit=crop",
    rating: 4.8,
    reviews: 98,
    description: "Premium 10-piece non-stick cookware set including pots, pans, and lids. Heat-resistant handles and dishwasher safe.",
  },
  {
    id: "3",
    name: "Electric Kettle 1.7L",
    category: "Kitchen Appliances",
    price: 2500,
    image: electricKettleImg,
    rating: 4.3,
    reviews: 215,
    description: "Fast-boiling stainless steel electric kettle with auto shut-off and boil-dry protection. 1.7L capacity.",
  },
  {
    id: "4",
    name: "Kitchen Knife Set",
    category: "Utensils",
    price: 4200,
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&h=500&fit=crop",
    rating: 4.7,
    reviews: 156,
    description: "Professional 8-piece knife set with ergonomic handles and protective sheaths. Made from high-carbon stainless steel.",
  },
  {
    id: "5",
    name: "Wireless Bluetooth Speaker",
    category: "Electronics",
    price: 3800,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop",
    rating: 4.6,
    reviews: 189,
    description: "Portable waterproof speaker with 12-hour battery life. Crystal clear sound and deep bass.",
  },
  {
    id: "6",
    name: "Blender 600W",
    category: "Kitchen Appliances",
    price: 5500,
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&h=500&fit=crop",
    rating: 4.4,
    reviews: 142,
    description: "Powerful 600W blender with multiple speed settings. Perfect for smoothies, soups, and crushing ice.",
  },
  {
    id: "7",
    name: "Stainless Steel Cutlery Set",
    category: "Utensils",
    price: 3200,
    image: cutlerySetImg,
    rating: 4.9,
    reviews: 203,
    description: "24-piece premium cutlery set. Mirror-polished finish and dishwasher safe.",
  },
  {
    id: "8",
    name: "Smart LED Desk Lamp",
    category: "Electronics",
    price: 2800,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&h=500&fit=crop",
    rating: 4.5,
    reviews: 91,
    description: "Adjustable LED lamp with touch controls and USB charging port. Multiple brightness levels and color temperatures.",
  },
  {
    id: "9",
    name: "Von Manual Air Fryer - 6.5L",
    category: "Kitchen Appliances",
    price: 8900,
    image: vonAirFryerImg,
    rating: 4.6,
    reviews: 87,
    description: "Von manual air fryer with 6.5L capacity. Manual control dials for precise temperature and time settings. Perfect for large family meals.",
  },
  {
    id: "10",
    name: "Thermos and 6 Cups Combo",
    category: "Accessories",
    price: 900,
    image: thermosCupsComboImg,
    rating: 4.4,
    reviews: 76,
    description: "Stainless steel thermos flask with 6 matching insulated cups. Perfect for outdoor activities, picnics, or keeping beverages hot/cold.",
  },
  {
    id: "11",
    name: "Electric Rice Cooker",
    category: "Kitchen Appliances",
    price: 4500,
    image: riceCookerImg,
    rating: 4.6,
    reviews: 132,
    description: "Multi-function rice cooker with digital display. Cooks rice, steams vegetables, and keeps food warm. 1.8L capacity perfect for families.",
  },
  {
    id: "12",
    name: "Microwave Oven 20L",
    category: "Kitchen Appliances",
    price: 7800,
    image: microwaveImg,
    rating: 4.5,
    reviews: 98,
    description: "Digital microwave oven with 20L capacity and 800W power. Multiple cooking presets and defrost function.",
  },
  {
    id: "13",
    name: "Water Dispenser Hot & Cold",
    category: "Kitchen Appliances",
    price: 9500,
    image: waterDispenserImg,
    rating: 4.7,
    reviews: 164,
    description: "Hot and cold water dispenser with LED display. Energy efficient with child safety lock. Compatible with standard water bottles.",
  },
  {
    id: "14",
    name: "Pressure Cooker 6L",
    category: "Cookware",
    price: 3800,
    image: pressureCookerImg,
    rating: 4.8,
    reviews: 201,
    description: "Stainless steel pressure cooker with multiple safety features. Reduces cooking time by up to 70%. Perfect for stews and rice.",
  },
  {
    id: "15",
    name: "Food Processor 600W",
    category: "Kitchen Appliances",
    price: 6200,
    image: foodProcessorImg,
    rating: 4.4,
    reviews: 87,
    description: "Multi-function food processor with multiple attachments. Chops, slices, shreds, and blends. 2L bowl capacity.",
  },
  {
    id: "16",
    name: "2-Slice Toaster",
    category: "Kitchen Appliances",
    price: 2200,
    image: toasterImg,
    rating: 4.3,
    reviews: 115,
    description: "Stainless steel toaster with adjustable browning control. Wide slots for thick bread. Removable crumb tray for easy cleaning.",
  },
  {
    id: "17",
    name: "Steam Iron Box",
    category: "Electronics",
    price: 1800,
    image: ironBoxImg,
    rating: 4.5,
    reviews: 143,
    description: "Steam iron with ceramic soleplate and adjustable temperature control. Anti-drip system and self-cleaning function.",
  },
  {
    id: "18",
    name: "Cotton Bedsheets Set",
    category: "Home & Living",
    price: 2500,
    image: bedsheetsSetImg,
    rating: 4.6,
    reviews: 178,
    description: "Premium cotton bedsheet set including fitted sheet, flat sheet, and 2 pillowcases. Soft, breathable, and machine washable.",
  },
  {
    id: "19",
    name: "Bath Towel Set (6 Pieces)",
    category: "Home & Living",
    price: 1800,
    image: towelSetImg,
    rating: 4.7,
    reviews: 156,
    description: "Soft cotton bath towel set in assorted colors. Highly absorbent and quick-drying. Includes 2 bath towels and 4 hand towels.",
  },
  {
    id: "20",
    name: "Porcelain Dinner Set 24 Pieces",
    category: "Utensils",
    price: 5500,
    image: dinnerSetImg,
    rating: 4.8,
    reviews: 92,
    description: "Elegant 24-piece dinner set with gold trim. Includes plates, bowls, and serving dishes. Microwave and dishwasher safe.",
  },
  {
    id: "21",
    name: "Water Filter Pitcher",
    category: "Kitchen Appliances",
    price: 1500,
    image: waterFilterImg,
    rating: 4.4,
    reviews: 124,
    description: "2.5L water filter pitcher with advanced filtration system. Removes chlorine, sediment, and improves taste. Includes 1 filter.",
  },
  {
    id: "22",
    name: "Vacuum Cleaner 1200W",
    category: "Electronics",
    price: 8500,
    image: vacuumCleanerImg,
    rating: 4.6,
    reviews: 89,
    description: "Powerful bagless vacuum cleaner with HEPA filter. Perfect for carpets and hard floors. 5L dust capacity with washable filter.",
  },
  {
    id: "23",
    name: "Standing Fan 16 Inch",
    category: "Electronics",
    price: 3200,
    image: standingFanImg,
    rating: 4.5,
    reviews: 167,
    description: "Oscillating standing fan with remote control. 3-speed settings and timer function. Adjustable height and quiet operation.",
  },
  {
    id: "24",
    name: "Modern Wall Clock",
    category: "Home & Living",
    price: 1200,
    image: wallClockImg,
    rating: 4.3,
    reviews: 201,
    description: "Silent quartz wall clock with minimalist design. Clear numbers and smooth movement. Battery operated (battery not included).",
  },
  {
    id: "25",
    name: "Food Storage Containers Set",
    category: "Accessories",
    price: 1600,
    image: storageContainersImg,
    rating: 4.6,
    reviews: 143,
    description: "12-piece clear plastic food storage container set with snap-lock lids. Microwave, freezer, and dishwasher safe. Various sizes.",
  },
  {
    id: "26",
    name: "Large Laundry Basket",
    category: "Home & Living",
    price: 950,
    image: laundryBasketImg,
    rating: 4.4,
    reviews: 98,
    description: "Durable plastic laundry basket with ventilation holes and comfortable handles. 45L capacity. Available in various colors.",
  },
  {
    id: "27",
    name: "Spin Mop and Bucket Set",
    category: "Home & Living",
    price: 2200,
    image: mopBucketSetImg,
    rating: 4.7,
    reviews: 187,
    description: "360° rotating spin mop with bucket and wringer. Microfiber mop head is machine washable. Makes floor cleaning effortless.",
  },
  {
    id: "28",
    name: "Dish Drying Rack",
    category: "Accessories",
    price: 1400,
    image: dishRackImg,
    rating: 4.5,
    reviews: 134,
    description: "Stainless steel dish rack with draining tray. Compact design with cutlery holder. Rust-resistant and easy to clean.",
  },
  {
    id: "29",
    name: "Wooden Spice Rack with Jars",
    category: "Accessories",
    price: 1800,
    image: spiceRackImg,
    rating: 4.6,
    reviews: 76,
    description: "Wall-mounted spice rack with 12 glass jars. Keeps spices organized and easily accessible. Includes labels.",
  },
  {
    id: "30",
    name: "Porcelain Tea Set",
    category: "Utensils",
    price: 3500,
    image: teaSetImg,
    rating: 4.8,
    reviews: 112,
    description: "Elegant 7-piece tea set with gold trim. Includes teapot and 6 cups with saucers. Perfect for entertaining guests.",
  },
  {
    id: "31",
    name: "Hand Blender 300W",
    category: "Kitchen Appliances",
    price: 2800,
    image: handBlenderImg,
    rating: 4.4,
    reviews: 89,
    description: "Powerful hand blender with stainless steel shaft. Multiple speed settings for blending soups, smoothies, and baby food.",
  },
  {
    id: "32",
    name: "Sandwich Maker",
    category: "Kitchen Appliances",
    price: 2200,
    image: sandwichMakerImg,
    rating: 4.3,
    reviews: 145,
    description: "Non-stick sandwich maker with indicator lights. Makes perfectly toasted sandwiches in minutes. Compact design.",
  },
  {
    id: "33",
    name: "Electric Kettle Jug 1.8L",
    category: "Kitchen Appliances",
    price: 2800,
    image: electricJugImg,
    rating: 4.5,
    reviews: 198,
    description: "Large capacity electric jug with LED indicator. Cordless design with 360° rotational base. Auto shut-off feature.",
  },
  {
    id: "34",
    name: "Juicer Machine",
    category: "Kitchen Appliances",
    price: 5800,
    image: juicerImg,
    rating: 4.6,
    reviews: 76,
    description: "Powerful juicer for extracting fresh juice from fruits and vegetables. Easy to clean with detachable parts.",
  },
  {
    id: "35",
    name: "Deep Fryer 3.5L",
    category: "Kitchen Appliances",
    price: 6500,
    image: deepFryerImg,
    rating: 4.5,
    reviews: 93,
    description: "Stainless steel deep fryer with adjustable temperature control. Removable basket and cool-touch handle for safety.",
  },
  {
    id: "36",
    name: "Wireless Headphones",
    category: "Electronics",
    price: 3200,
    image: headphonesImg,
    rating: 4.7,
    reviews: 234,
    description: "Bluetooth over-ear headphones with soft padding. Long battery life and excellent sound quality for music and calls.",
  },
  {
    id: "37",
    name: "Power Bank 20000mAh",
    category: "Electronics",
    price: 2500,
    image: powerBankImg,
    rating: 4.6,
    reviews: 312,
    description: "High capacity power bank with LED display. Fast charging for multiple devices. Compact and portable design.",
  },
  {
    id: "38",
    name: "Charging Cables 3-Pack",
    category: "Electronics",
    price: 800,
    image: chargingCablesImg,
    rating: 4.4,
    reviews: 267,
    description: "Durable braided charging cables with multiple connectors. USB-C, Micro USB, and Lightning compatible. 1.5m length.",
  },
  {
    id: "39",
    name: "Car Phone Holder",
    category: "Accessories",
    price: 650,
    image: phoneHolderImg,
    rating: 4.5,
    reviews: 189,
    description: "Universal car phone mount with adjustable grip. Dashboard or windshield mounting. 360° rotation for optimal viewing.",
  },
  {
    id: "40",
    name: "Hair Dryer 1800W",
    category: "Electronics",
    price: 2400,
    image: hairDryerImg,
    rating: 4.5,
    reviews: 156,
    description: "Professional hair dryer with diffuser attachment. Multiple heat and speed settings. Cool shot button for styling.",
  },
  {
    id: "41",
    name: "Rechargeable Hair Clipper",
    category: "Electronics",
    price: 2800,
    image: hairClipperImg,
    rating: 4.6,
    reviews: 203,
    description: "Professional hair clipper with multiple guide combs. Cordless operation with long battery life. Suitable for home use.",
  },
  {
    id: "42",
    name: "Digital Weighing Scale",
    category: "Electronics",
    price: 1500,
    image: weighingScaleImg,
    rating: 4.4,
    reviews: 187,
    description: "Tempered glass bathroom scale with LCD display. Accurate weight measurement up to 180kg. Auto on/off feature.",
  },
  {
    id: "43",
    name: "Laptop Cooling Pad",
    category: "Electronics",
    price: 1800,
    image: laptopCoolerImg,
    rating: 4.5,
    reviews: 98,
    description: "Dual fan laptop cooler with adjustable height. USB powered with quiet operation. Fits laptops up to 17 inches.",
  },
  {
    id: "44",
    name: "Wireless Mouse",
    category: "Electronics",
    price: 950,
    image: wirelessMouseImg,
    rating: 4.3,
    reviews: 245,
    description: "Ergonomic wireless mouse with smooth tracking. Long battery life and plug-and-play USB receiver. Silent clicking.",
  },
  {
    id: "45",
    name: "RGB Gaming Keyboard",
    category: "Electronics",
    price: 3500,
    image: keyboardImg,
    rating: 4.7,
    reviews: 176,
    description: "Mechanical keyboard with customizable RGB backlighting. Responsive keys for gaming and typing. Anti-ghosting technology.",
  },
  {
    id: "46",
    name: "HD Webcam 1080p",
    category: "Electronics",
    price: 2200,
    image: webcamImg,
    rating: 4.5,
    reviews: 134,
    description: "High definition webcam with built-in microphone. Perfect for video calls and streaming. Plug and play USB connection.",
  },
  {
    id: "47",
    name: "Laptop Backpack",
    category: "Accessories",
    price: 2500,
    image: laptopBagImg,
    rating: 4.6,
    reviews: 198,
    description: "Water-resistant laptop bag with multiple compartments. Fits laptops up to 15.6 inches. Padded straps for comfort.",
  },
  {
    id: "48",
    name: "Extension Socket with USB",
    category: "Electronics",
    price: 1200,
    image: extensionSocketImg,
    rating: 4.7,
    reviews: 289,
    description: "4-way extension socket with 2 USB ports. Surge protection and safety switches. Compact design for home and office.",
  },
  {
    id: "49",
    name: "Memory Foam Pillow",
    category: "Home & Living",
    price: 1800,
    image: pillowImg,
    rating: 4.6,
    reviews: 167,
    description: "Ergonomic memory foam pillow for neck support. Hypoallergenic cover that's machine washable. Perfect for side sleepers.",
  },
  {
    id: "50",
    name: "Duvet Comforter",
    category: "Home & Living",
    price: 3500,
    image: duvetImg,
    rating: 4.7,
    reviews: 145,
    description: "Soft and warm duvet with elegant stitching. Lightweight yet provides excellent insulation. Machine washable and durable.",
  },
  {
    id: "51",
    name: "Decorative Throw Pillows Set",
    category: "Home & Living",
    price: 1600,
    image: throwPillowsImg,
    rating: 4.5,
    reviews: 112,
    description: "Set of 4 decorative throw pillows in various colors and patterns. Soft fabric covers with zipper closure. Adds style to any room.",
  },
  {
    id: "52",
    name: "Modern Table Lamp",
    category: "Home & Living",
    price: 2200,
    image: tableLampImg,
    rating: 4.6,
    reviews: 98,
    description: "Elegant table lamp with fabric shade. Provides warm ambient lighting. Perfect for bedroom or living room. E27 bulb socket.",
  },
  {
    id: "53",
    name: "Canvas Wall Art Set",
    category: "Home & Living",
    price: 3200,
    image: wallArtImg,
    rating: 4.5,
    reviews: 87,
    description: "Set of 3 modern canvas prints with wooden frames. Ready to hang with included hardware. Adds artistic touch to any space.",
  },
  {
    id: "54",
    name: "Geometric Area Rug",
    category: "Home & Living",
    price: 4500,
    image: areaRugImg,
    rating: 4.6,
    reviews: 76,
    description: "Modern geometric pattern area rug. Soft and durable material that's easy to clean. Available in 150x200cm size.",
  },
  {
    id: "55",
    name: "Blackout Curtains Set",
    category: "Home & Living",
    price: 2800,
    image: curtainsImg,
    rating: 4.7,
    reviews: 156,
    description: "Thermal insulated blackout curtains with rod pocket. Blocks sunlight and reduces noise. Set of 2 panels. Machine washable.",
  },
  {
    id: "56",
    name: "Shower Curtain with Hooks",
    category: "Home & Living",
    price: 1200,
    image: showerCurtainImg,
    rating: 4.4,
    reviews: 134,
    description: "Waterproof shower curtain with modern geometric pattern. Includes 12 rust-proof hooks. Mildew resistant and easy to clean.",
  },
  {
    id: "57",
    name: "Bathroom Shelf Organizer",
    category: "Home & Living",
    price: 1800,
    image: bathroomOrganizerImg,
    rating: 4.5,
    reviews: 123,
    description: "Chrome-plated wall-mounted bathroom organizer. 5 tiers for storing toiletries and towels. Rust-resistant and easy to install.",
  },
  {
    id: "58",
    name: "Plastic Storage Box Large",
    category: "Home & Living",
    price: 1200,
    image: storageBoxImg,
    rating: 4.4,
    reviews: 198,
    description: "Clear plastic storage container with secure lid. 50L capacity for organizing clothes, toys, or documents. Stackable design.",
  },
  {
    id: "59",
    name: "8-Tier Shoe Rack",
    category: "Home & Living",
    price: 2800,
    image: shoeRackImg,
    rating: 4.6,
    reviews: 167,
    description: "Metal shoe rack with 8 tiers. Holds up to 32 pairs of shoes. Sturdy construction with wheels for easy movement.",
  },
  {
    id: "60",
    name: "Velvet Hangers 20-Pack",
    category: "Home & Living",
    price: 1400,
    image: hangersImg,
    rating: 4.7,
    reviews: 234,
    description: "Non-slip velvet hangers with 360° swivel hook. Space-saving slim design. Prevents clothes from slipping. Assorted colors.",
  },
  {
    id: "61",
    name: "Decorative Wall Mirror",
    category: "Home & Living",
    price: 3500,
    image: mirrorImg,
    rating: 4.6,
    reviews: 89,
    description: "Elegant wall mirror with ornate gold frame. 60x80cm size. High-quality glass with clear reflection. Adds elegance to any room.",
  },
  {
    id: "62",
    name: "Pedal Trash Can 12L",
    category: "Home & Living",
    price: 2200,
    image: trashCanImg,
    rating: 4.5,
    reviews: 176,
    description: "Stainless steel trash can with foot pedal and lid. Fingerprint-resistant finish. Removable inner bucket for easy cleaning.",
  },
  {
    id: "63",
    name: "Yoga Mat with Strap",
    category: "Sports & Fitness",
    price: 1500,
    image: yogaMatImg,
    rating: 4.6,
    reviews: 203,
    description: "Non-slip yoga mat with carrying strap. 6mm thick for cushioning and support. Easy to clean and roll up. Perfect for home workouts.",
  },
  {
    id: "64",
    name: "Adjustable Dumbbells 20kg",
    category: "Sports & Fitness",
    price: 4500,
    image: dumbbellsImg,
    rating: 4.7,
    reviews: 145,
    description: "Adjustable dumbbell set with multiple weight plates. Includes carrying case. Perfect for home gym and strength training.",
  },
  {
    id: "65",
    name: "Digital Jump Rope",
    category: "Sports & Fitness",
    price: 850,
    image: jumpRopeImg,
    rating: 4.4,
    reviews: 178,
    description: "Jump rope with digital counter and timer. Adjustable length with comfortable handles. Great for cardio workouts.",
  },
  {
    id: "66",
    name: "Sports Water Bottle 1L",
    category: "Sports & Fitness",
    price: 650,
    image: waterBottleImg,
    rating: 4.5,
    reviews: 289,
    description: "BPA-free water bottle with time markers. Leak-proof lid and wide mouth for easy cleaning. Perfect for gym and outdoor activities.",
  },
  {
    id: "67",
    name: "Lunch Box with Compartments",
    category: "Accessories",
    price: 950,
    image: lunchBoxImg,
    rating: 4.4,
    reviews: 156,
    description: "Microwave-safe lunch box with 3 compartments. Leak-proof design with secure clips. BPA-free material. Includes cutlery.",
  },
  {
    id: "68",
    name: "Digital Alarm Clock",
    category: "Electronics",
    price: 1200,
    image: alarmClockImg,
    rating: 4.5,
    reviews: 198,
    description: "LED display alarm clock with USB charging port. Snooze function and adjustable brightness. Temperature display. Dual alarms.",
  },
  {
    id: "69",
    name: "Desk Organizer Wood",
    category: "Accessories",
    price: 1800,
    image: deskOrganizerImg,
    rating: 4.6,
    reviews: 134,
    description: "Wooden desk organizer with multiple compartments. Holds pens, phone, documents, and accessories. Natural wood finish.",
  },
  {
    id: "70",
    name: "Ergonomic Office Chair",
    category: "Furniture",
    price: 12500,
    image: officeChairImg,
    rating: 4.7,
    reviews: 167,
    description: "Adjustable office chair with lumbar support. PU leather upholstery with high-density foam. Swivel base with smooth-rolling casters.",
  },
  {
    id: "71",
    name: "Computer Desk with Drawer",
    category: "Furniture",
    price: 9500,
    image: computerDeskImg,
    rating: 4.6,
    reviews: 145,
    description: "Wooden computer desk with storage drawer and shelf. Spacious tabletop for laptop and accessories. Easy assembly.",
  },
  {
    id: "72",
    name: "5-Tier Bookshelf",
    category: "Furniture",
    price: 8500,
    image: bookshelfImg,
    rating: 4.5,
    reviews: 123,
    description: "Wooden bookshelf with 5 open shelves. Sturdy construction for books and decorative items. Modern design fits any room.",
  },
  {
    id: "73",
    name: "Foldable Drying Rack",
    category: "Home & Living",
    price: 2200,
    image: dryingRackImg,
    rating: 4.4,
    reviews: 189,
    description: "Large capacity clothes drying rack. Folds flat for easy storage. Rust-resistant metal frame. Indoor and outdoor use.",
  },
  {
    id: "74",
    name: "Ironing Board Adjustable",
    category: "Home & Living",
    price: 3200,
    image: ironingBoardImg,
    rating: 4.5,
    reviews: 156,
    description: "Height-adjustable ironing board with cotton cover. Iron rest and sturdy legs. Foldable design for easy storage.",
  },
  {
    id: "75",
    name: "Broom and Dustpan Set",
    category: "Home & Living",
    price: 850,
    image: broomSetImg,
    rating: 4.3,
    reviews: 234,
    description: "Long-handle broom with dustpan combo. Soft bristles for effective sweeping. Hanging loop for convenient storage.",
  },
  {
    id: "76",
    name: "Toilet Brush with Holder",
    category: "Home & Living",
    price: 650,
    image: toiletBrushImg,
    rating: 4.4,
    reviews: 198,
    description: "Modern toilet brush with covered holder. Durable bristles and sturdy handle. Sleek design that complements any bathroom.",
  },
  {
    id: "77",
    name: "Cleaning Gloves Rubber",
    category: "Home & Living",
    price: 350,
    image: cleaningGlovesImg,
    rating: 4.5,
    reviews: 267,
    description: "Heavy-duty rubber cleaning gloves. Protects hands from chemicals and hot water. Non-slip grip. Reusable and durable.",
  },
];

export const categories = [
  "All",
  "Kitchen Appliances",
  "Cookware",
  "Utensils",
  "Electronics",
  "Accessories",
  "Home & Living",
  "Sports & Fitness",
  "Furniture",
];
