import { Product } from "@/components/ProductCard";
import electricKettleImg from "@/assets/electric-kettle.jpg";
import cutlerySetImg from "@/assets/cutlery-set.jpg";
import airFryerImg from "@/assets/air-fryer.jpg";
import vonAirFryerImg from "@/assets/von-air-fryer.jpg";

export const products: Product[] = [
  {
    id: "1",
    name: "Stainless Steel Air Fryer",
    category: "Kitchen Appliances",
    price: 8500,
    image: airFryerImg,
    rating: 4.5,
    reviews: 124,
    description: "5L capacity air fryer with digital controls and 8 preset cooking modes. Perfect for healthy cooking with little to no oil.",
  },
  {
    id: "2",
    name: "Non-Stick Cookware Set",
    category: "Cookware",
    price: 12000,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&h=500&fit=crop",
    rating: 4.8,
    reviews: 98,
    description: "Premium 10-piece non-stick cookware set including pots, pans, and lids. Heat-resistant handles and dishwasher safe.",
  },
  {
    id: "3",
    name: "Electric Kettle 1.7L",
    category: "Kitchen Appliances",
    price: 2500,
    image: electricKettleImg,
    rating: 4.3,
    reviews: 215,
    description: "Fast-boiling stainless steel electric kettle with auto shut-off and boil-dry protection. 1.7L capacity.",
  },
  {
    id: "4",
    name: "Kitchen Knife Set",
    category: "Utensils",
    price: 4200,
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&h=500&fit=crop",
    rating: 4.7,
    reviews: 156,
    description: "Professional 8-piece knife set with ergonomic handles and protective sheaths. Made from high-carbon stainless steel.",
  },
  {
    id: "5",
    name: "Wireless Bluetooth Speaker",
    category: "Electronics",
    price: 3800,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop",
    rating: 4.6,
    reviews: 189,
    description: "Portable waterproof speaker with 12-hour battery life. Crystal clear sound and deep bass.",
  },
  {
    id: "6",
    name: "Blender 600W",
    category: "Kitchen Appliances",
    price: 5500,
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&h=500&fit=crop",
    rating: 4.4,
    reviews: 142,
    description: "Powerful 600W blender with multiple speed settings. Perfect for smoothies, soups, and crushing ice.",
  },
  {
    id: "7",
    name: "Stainless Steel Cutlery Set",
    category: "Utensils",
    price: 3200,
    image: cutlerySetImg,
    rating: 4.9,
    reviews: 203,
    description: "24-piece premium cutlery set. Mirror-polished finish and dishwasher safe.",
  },
  {
    id: "8",
    name: "Smart LED Desk Lamp",
    category: "Electronics",
    price: 2800,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&h=500&fit=crop",
    rating: 4.5,
    reviews: 91,
    description: "Adjustable LED lamp with touch controls and USB charging port. Multiple brightness levels and color temperatures.",
  },
  {
    id: "9",
    name: "Von Manual Air Fryer - 6.5L",
    category: "Kitchen Appliances",
    price: 8900,
    image: vonAirFryerImg,
    rating: 4.6,
    reviews: 87,
    description: "Von manual air fryer with 6.5L capacity. Manual control dials for precise temperature and time settings. Perfect for large family meals.",
  },
];

export const categories = [
  "All",
  "Kitchen Appliances",
  "Cookware",
  "Utensils",
  "Electronics",
  "Accessories",
];
